---@type table<string, Lever>
BRIDGE_LEVER_ALIAS = BRIDGE_LEVER_ALIAS or {}
BRIDGE_LEVER_ALIAS["aNHB_3d"] = LEVERS["NHB5R"] -- 3番線 潮凪浜方
--BRIDGE_LEVER_ALIAS["aNHB_3u"]=LEVERS[""] -- 3番線 掘戸方
BRIDGE_LEVER_ALIAS["aNHB_4d"] = LEVERS["NHB4R"] -- 4番線 潮凪浜方
BRIDGE_LEVER_ALIAS["aAKA_D"] = LEVERS["WAK_SGN4"]
BRIDGE_LEVER_ALIAS["aAKA_U"] = LEVERS["WAK4L"]
BRIDGE_LEVER_ALIAS["aONL_D"] = LEVERS["WAK_SGN1"]
BRIDGE_LEVER_ALIAS["aONL_U"] = LEVERS["SGN_WAK3"]
BRIDGE_LEVER_ALIAS["aKGM_D"] = LEVERS["SGN_SNH2"]
BRIDGE_LEVER_ALIAS["aKGM_U"] = LEVERS["SNH_SGN2"]
--BRIDGE_LEVER_ALIAS["aSNH_D"] = LEVERS[""] -- 2番線 入守山方
BRIDGE_LEVER_ALIAS["aSNH_U"] = LEVERS["SNH2L"] -- 1番線 掘戸方
--BRIDGE_LEVER_ALIAS["aSNH_Ud"] = LEVERS[""] -- 1番線 入守山方
