### 北港駅 ###
[NHB4R]
start = "NHB4LT"
destination = "NHB_WAK1T"
direction = "right"
switches = [{ sw = "NHB21", t = "reverse" }, { sw = "NHB22", t = "normal" }]
route_lock = ["NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB_WAK1T"]

approach_track = ["NHB4LT"]
approach_lock_time = 20

update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK1R")'
# StandardAspectCallback_3rd_multi({"WAK1R","WAK2R"})

[NHB5R]
start = "NHB5LT"
destination = "NHB_WAK1T"
direction = "right"
switches = [{ sw = "NHB21", t = "normal" }, { sw = "NHB22", t = "normal" }]
route_lock = ["NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB_WAK1T"]

approach_track = ["NHB5LT"]
approach_lock_time = 20

update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK1R")'
# StandardAspectCallback_3rd_multi({"WAK1R","WAK2R"})

[NHB11R]
start = "NHB4LT"
destination = "NHB13RT"
direction = "right"
switches = [{ sw = "NHB21", t = "reverse" }, { sw = "NHB22", t = "reverse" }]
route_lock = ["NHB21T", "NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB22T", "NHB13RT"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_2nd(1)'

[NHB12R]
start = "NHB5LT"
destination = "NHB13RT"
direction = "right"
switches = [{ sw = "NHB21", t = "normal" }, { sw = "NHB22", t = "reverse" }]
route_lock = ["NHB21T", "NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB22T", "NHB13RT"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_2nd(1)'

[NHB13R]
start = "NHB6LT"
destination = "NHB13RT"
direction = "right"
switches = [{ sw = "NHB31", t = "normal" }, { sw = "NHB22", t = "normal" }]
route_lock = ["NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB13RT"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_2nd(1)'

[NHB4L]
start = "WAK_NHB1T"
destination = "NHB4LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "reverse" }]
route_lock = ["NHB13RT", "NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB13RT", "NHB22T", "NHB21T", "NHB4LT"]

approach_track = ["WAK_NHB1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_2nd(2)'

[NHB5L]
start = "WAK_NHB1T"
destination = "NHB5LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "normal" }]
route_lock = ["NHB13RT", "NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB13RT", "NHB22T", "NHB21T", "NHB5LT"]

approach_track = ["WAK_NHB1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_2nd(2)'

[NHB6L]
start = "WAK_NHB1T"
destination = "NHB6LT"
direction = "left"
switches = [{ sw = "NHB22", t = "normal" }, { sw = "NHB31", t = "normal" }]
route_lock = ["NHB13RT", "NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB13RT", "NHB22T", "NHB6LT"]

approach_track = ["WAK_NHB1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_2nd(2)'

[NHB11L]
start = "NHB13RT"
destination = "NHB4LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "reverse" }]
route_lock = ["NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB21T", "NHB4LT"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_2nd(1)'

[NHB12L]
start = "NHB13RT"
destination = "NHB5LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "normal" }]
route_lock = ["NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB21T", "NHB5LT"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_2nd(1)'

[NHB13L]
start = "NHB13RT"
destination = "NHB6LT"
direction = "left"
switches = [{ sw = "NHB22", t = "normal" }, { sw = "NHB31", t = "normal" }]
route_lock = ["NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB6LT"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_2nd(1)'

### 北尾信号場 ###

[WAK1R]
start = "NHB_WAK1T"
destination = "WAK_SGN5T"
direction = "right"
switches = [{ sw = "WAK11", t = "normal" }]
route_lock = ["WAK1RT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["WAK1RT", "WAK_SGN5T"]

approach_track = ["NHB_WAK1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK_SGN4")'

[WAK4L]
start = "SGN_WAK1T"
destination = "WAK_NHB1T"
direction = "left"
switches = [{ sw = "WAK11", t = "normal" }, { sw = "WAK12", t = "normal" }]
route_lock = ["WAK4LT", "WAK11T", "WAK12T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["WAK4LT", "WAK11T", "WAK12T", "WAK_NHB1T"]

approach_track = ["SGN_WAK1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_3rd_multi({"NHB4L","NHB5L","NHB6L"})'

### 北尾・大熊間 ###

[WAK_SGN4]
auto = true
direction = "right"
signal_track = ["WAK_SGN4T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK_SGN3")'

[WAK_SGN3]
auto = true
direction = "right"
signal_track = ["WAK_SGN3T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK_SGN2")'

[WAK_SGN2]
auto = true
direction = "right"
signal_track = ["WAK_SGN2T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK_SGN1")'

[WAK_SGN1]
auto = true
direction = "right"
signal_track = ["WAK_SGN1T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN1R")'

[SGN_WAK5]
auto = true
direction = "left"
signal_track = ["SGN_WAK5T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_WAK4")'

[SGN_WAK4]
auto = true
direction = "right"
signal_track = ["SGN_WAK4T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_WAK3")'

[SGN_WAK3]
auto = true
direction = "left"
signal_track = ["SGN_WAK3T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_WAK2")'

[SGN_WAK2]
auto = true
direction = "left"
signal_track = ["SGN_WAK2T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_WAK1")'

[SGN_WAK1]
auto = true
direction = "left"
signal_track = ["SGN_WAK1T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("WAK4L")'

### 大熊駅 ###

[SGN1R]
start = "WAK_SGN1T"
destination = "SGN1RT"
direction = "right"
switches = []
route_lock = []

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SGN1RT"]

approach_track = ["WAK_SGN1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_3rd_multi({"SGN2R"})'

[SGN2R]
start = "SGN1RT"
destination = "SGN_SNH4T"
direction = "right"
switches = [{ sw = "SGN21", t = "normal" }]
route_lock = ["SGN2RT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SGN2RT", "SGN_SNH4T"]

approach_track = []
approach_lock_time = 0

update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_SNH3")'

#[SGN11R]
#start = "SGN1RT"
#destination = "SGN3RT"
#direction = "right"
#switches = [{ sw = "SGN21", t = "reverse" }, { sw = "SGN22", t = "reverse" }]
#route_lock = ["SGN2RT", "SGN21T"]
#
#overrun_lock = []
#overrun_lock_time = 0
#
#signal_track = ["SGN2RT", "SGN21T", "SGN3RT"]
#
#approach_track = []
#approach_lock_time = 0
#
#update_callback = 'StandardAspectCallback_2nd(1)'
#
#[SGN11L]
#start = "SGN3RT"
#destination = "SGN1RT"
#direction = "left"
#switches = [{ sw = "SGN21", t = "reverse" }, { sw = "SGN22", t = "reverse" }]
#route_lock = ["SGN21T", "SGN2RT"]
#
#overrun_lock = []
#overrun_lock_time = 0
#
#signal_track = ["SGN21T", "SGN2RT", "SGN1RT"]
#
#approach_track = []
#approach_lock_time = 0
#
#update_callback = 'StandardAspectCallback_2nd(1)'
#
#[SGN12R]
#start = "SGN_WAK6T"
#destination = "SGN12RT"
#direction = "right"
#switches = [{ sw = "SGN22", t = "reverse" }]
#route_lock = ["SGN22T"]
#
#overrun_lock = []
#overrun_lock_time = 0
#
#signal_track = ["SGN22T", "SGN12RT"]
#
#approach_track = []
#approach_lock_time = 0
#
#update_callback = 'StandardAspectCallback_2nd(1)'
#
#[SGN12L]
#start = "SGN12RT"
#destination = "SGN_WAK6T"
#direction = "right"
#switches = [{ sw = "SGN22", t = "reverse" }]
#route_lock = ["SGN22T"]
#
#overrun_lock = []
#overrun_lock_time = 0
#
#signal_track = ["SGN22T", "SGN_WAK6T"]
#
#approach_track = []
#approach_lock_time = 0
#
#update_callback = 'StandardAspectCallback_2nd(1)'

[SGN5L]
start = "SNH_SGN1T"
destination = "SGN_WAK6T"
direction = "left"
switches = [{ sw = "SGN21", t = "normal" }, { sw = "SGN22", t = "normal" }]
route_lock = ["SGN5LT", "SGN21T", "SGN22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SGN5LT", "SGN21T", "SGN22T", "SGN_WAK6T"]

approach_track = ["SNH_SGN1T"]
approach_lock_time = 40

update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_WAK5")'

### 大熊・潮凪浜間 ###

[SGN_SNH3]
auto = true
direction = "right"
signal_track = ["SGN_SNH3T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_SNH2")'


[SGN_SNH2]
auto = true
direction = "right"
signal_track = ["SGN_SNH2T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN_SNH1")'


[SGN_SNH1]
auto = true
direction = "right"
signal_track = ["SGN_SNH1T"]
update_callback = """
function(self)
    if self.HR then
        if LEVERS["SNH1R"].HR and self.aspect >= 2 then
            return 3
        else
            return 2
        end
    else
        return 0
    end
end
"""

[SNH_SGN3]
auto = true
direction = "left"
signal_track = ["SNH_SGN3T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SNH_SGN2")'

[SNH_SGN2]
auto = true
direction = "left"
signal_track = ["SNH_SGN2T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SNH_SGN1")'

[SNH_SGN1]
auto = true
direction = "left"
signal_track = ["SNH_SGN1T"]
update_callback = 'StandardAspectCallback_3rd_G_Y_R("SGN5L")'

### 潮凪浜駅 ###

[SNH1R]
start = "SGN_SNH1T"
destination = "SNH1RT"
direction = "right"
switches = []
route_lock = []

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH1RT"]

approach_track = ["SGN_SNH1T"]
approach_lock_time = 20

update_callback = 'StandardAspectCallback_2nd(1)'


[SNH2L]
start = "SNH4LT"
destination = "SNH_SGN4T"
direction = "left"
switches = [{ sw = "SNH22", t = "normal" }]
route_lock = ["SNH22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH22T", "SNH_SGN4T"]

approach_track = ["SNH4LT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_3rd_G_Y_R("SNH_SGN3")'


[SNH11R]
start = "SNH1RT"
destination = "SNH3RT"
direction = "right"
switches = [{ sw = "SNH21", t = "normal" }]
route_lock = ["SNH21AT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH21AT", "SNH3RT"]

approach_track = ["SNH1RT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_2nd(1)'

[SNH11L]
start = "SNH3RT"
destination = "SNH1RT"
direction = "left"
switches = [{ sw = "SNH21", t = "normal" }]
route_lock = ["SNH21AT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH21AT", "SNH1RT"]

approach_track = ["SNH3RT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_2nd(1)'
[SNH12R]
start = "SNH4LT"
destination = "SNH3RT"
direction = "right"
switches = [{ sw = "SNH21", t = "reverse" }]
route_lock = ["SNH21BT", "SNH21AT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH21BT", "SNH21AT", "SNH3RT"]

approach_track = ["SNH4LT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_2nd(1)'


[SNH12L]
start = "SNH3RT"
destination = "SNH4LT"
direction = "left"
switches = [{ sw = "SNH21", t = "reverse" }]
route_lock = ["SNH21AT", "SNH21BT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH21AT", "SNH21BT", "SNH4LT"]

approach_track = ["SNH3RT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_2nd(1)'

[SNH12LZ]
start = "SNH3RT"
destination = "SNH4LT"
direction = "left"
switches = [{ sw = "SNH21", t = "reverse" }]
route_lock = ["SNH21AT", "SNH21BT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH21AT", "SNH21BT"]

approach_track = ["SNH3RT"]
approach_lock_time = 15

update_callback = """
function(self)
    if self.HR and TRACKS["SNH4LT"].isShort then
        return 1
    else
        return 0
    end
end
"""

[SNH13R]
start = "SNH13LT"
destination = "SNH4LT"
direction = "right"
switches = [{ sw = "SNH22", t = "reverse" }]
route_lock = ["SNH22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH22T", "SNH4LT"]

approach_track = ["SNH13LT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_2nd(1)'

[SNH13RZ]
start = "SNH13LT"
destination = "SNH4LT"
direction = "right"
switches = [{ sw = "SNH22", t = "reverse" }]
route_lock = ["SNH22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH22T"]

approach_track = ["SNH13LT"]
approach_lock_time = 15

update_callback = """
function(self)
    if self.HR and TRACKS["SNH4LT"].isShort  then
        return 1
    else
        return 0
    end
end
"""

[SNH13L]
start = "SNH4LT"
destination = "SNH13LT"
direction = "left"
switches = [{ sw = "SNH22", t = "reverse" }]
route_lock = ["SNH22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["SNH22T", "SNH13LT"]

approach_track = ["SNH4LT"]
approach_lock_time = 15

update_callback = 'StandardAspectCallback_2nd(1)'
