[NHB4R]
start = "NHB4LT"
destination = "NHB_WAK1T"
direction = "right"
switches = [{ sw = "NHB21", t = "reverse" }, { sw = "NHB22", t = "normal" }]
route_lock = ["NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB_WAK1T"]

approach_track = ["NHB4LT"]
approach_lock_time = 20

update_callback = """
function(self)
    if self.HR then
--        if LEVERS["WAK1R"].aspect >= 2 or LEVERS["WAK2R"].aspect >= 2 then
        if LEVERS["WAK1R"].aspect >= 2 then
            return 4
        else
            return 2
        end
    else
        return 0
    end
end
"""

[NHB5R]
start = "NHB5LT"
destination = "NHB_WAK1T"
direction = "right"
switches = [{ sw = "NHB21", t = "normal" }, { sw = "NHB22", t = "normal" }]
route_lock = ["NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB_WAK1T"]

approach_track = ["NHB5LT"]
approach_lock_time = 20

update_callback = """
function(self)
    if self.HR then
--        if LEVERS["WAK1R"].aspect >= 2 or LEVERS["WAK2R"].aspect >= 2 then
        if LEVERS["WAK1R"].aspect >= 2 then
            return 4
        else
            return 2
        end
    else
        return 0
    end
end
"""

[NHB11R]
start = "NHB4LT"
destination = "NHB13RT"
direction = "right"
switches = [{ sw = "NHB21", t = "reverse" }, { sw = "NHB22", t = "reverse" }]
route_lock = ["NHB21T", "NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB22T", "NHB13RT"]

approach_track = []
approach_lock_time = 0

update_callback = """
function(self)
    if self.HR then
        return 1
    else
        return 0
    end
end
"""

[NHB12R]
start = "NHB5LT"
destination = "NHB13RT"
direction = "right"
switches = [{ sw = "NHB21", t = "normal" }, { sw = "NHB22", t = "reverse" }]
route_lock = ["NHB21T", "NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB21T", "NHB22T", "NHB13RT"]

approach_track = []
approach_lock_time = 0

update_callback = """
function(self)
    if self.HR then
        return 1
    else
        return 0
    end
end
"""

[NHB13R]
start = "NHB6LT"
destination = "NHB13RT"
direction = "right"
switches = [
    #{sw="NHB31", t="normal"},
    { sw = "NHB22", t = "normal" },
]
route_lock = ["NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB13RT"]

approach_track = []
approach_lock_time = 0

update_callback = """
function(self)
    if self.HR then
        return 1
    else
        return 0
    end
end
"""

[NHB4L]
start = "WAK_NHB1T"
destination = "NHB4LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "reverse" }]
route_lock = ["NHB13RT", "NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB13RT", "NHB22T", "NHB21T", "NHB4LT"]

approach_track = ["WAK_NHB1T"]
approach_lock_time = 40

update_callback = """
function(self)
    if self.HR then
        return 2
    else
        return 0
    end
end
"""

[NHB5L]
start = "WAK_NHB1T"
destination = "NHB5LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "normal" }]
route_lock = ["NHB13RT", "NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB13RT", "NHB22T", "NHB21T", "NHB5LT"]

approach_track = ["WAK_NHB1T"]
approach_lock_time = 40

update_callback = """
function(self)
    if self.HR then
        return 2
    else
        return 0
    end
end
"""

[NHB6L]
start = "WAK_NHB1T"
destination = "NHB6LT"
direction = "left"
switches = [
    { sw = "NHB22", t = "normal" },
    #{sw="NHB31", t="normal"},
]
route_lock = ["NHB13RT", "NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB13RT", "NHB22T", "NHB"]

approach_track = ["WAK_NHB1T"]
approach_lock_time = 40

update_callback = """
function(self)
    if self.HR then
        return 2
    else
        return 0
    end
end
"""

[NHB11L]
start = "NHB13RT"
destination = "NHB4LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "reverse" }]
route_lock = ["NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB21T", "NHB4LT"]

approach_track = []
approach_lock_time = 0

update_callback = """
function(self)
    if self.HR then
        return 1
    else
        return 0
    end
end
"""

[NHB12L]
start = "NHB13RT"
destination = "NHB5LT"
direction = "left"
switches = [{ sw = "NHB22", t = "reverse" }, { sw = "NHB21", t = "normal" }]
route_lock = ["NHB22T", "NHB21T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB21T", "NHB5LT"]

approach_track = []
approach_lock_time = 0

update_callback = """
function(self)
    if self.HR then
        return 1
    else
        return 0
    end
end
"""

[NHB13L]
start = "NHB13RT"
destination = "NHB6LT"
direction = "left"
switches = [
    { sw = "NHB22", t = "normal" },
    #{sw="NHB31", t="normal"},
]
route_lock = ["NHB22T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["NHB22T", "NHB"]

approach_track = []
approach_lock_time = 0

update_callback = """
function(self)
    if self.HR then
        return 1
    else
        return 0
    end
end
"""

[WAK_NHB1]
auto = true
direction = "left"
signal_track = ["WAK_NHB1T"]
update_callback = """
function(self)
    if self.HR then
        if LEVERS["NHB4L"].aspect >= 2 or LEVERS["NHB5L"].aspect >= 2 or LEVERS["NHB6L"].aspect >= 2 then
            return 4
        else
            return 2
        end
    else
        return 0
    end
end
"""

[WAK1R]
start = "NHB_WAK1T"
destination = "WAK_SGN5T"
direction = "right"
switches = [{ sw = "WAK11", t = "normal" }]
route_lock = ["WAK1RAT", "WAK1RBT"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["WAK1RAT", "WAK1RBT", "WAK_SGN5T"]

approach_track = ["NHB_WAK1T"]
approach_lock_time = 40

update_callback = """
function(self)
    if self.HR then
        if LEVERS["WAK_SGN4"].aspect >= 2 then
            return 4
        else
            return 2
        end
    else
        return 0
    end
end
"""

[WAK4L]
start = "SGN_WAK1T"
destination = "WAK12T"
direction = "left"
switches = [{ sw = "WAK11", t = "normal" }, { sw = "WAK12", t = "normal" }]
route_lock = ["WAK4LT", "WAK11T"]

overrun_lock = []
overrun_lock_time = 0

signal_track = ["WAK4LT", "WAK11T", "WAK12T"]

approach_track = ["SGN_WAK1T"]
approach_lock_time = 40

update_callback = """
function(self)
    if self.HR then
        if LEVERS["WAK_NHB1"].aspect >= 3 then
            return 4
        elseif LEVERS["WAK_NHB1"].aspect >= 2 then
            return 3
        else
            return 2
        end
    else
        return 0
    end
end
"""

[WAK_SGN4]
auto = true
direction = "right"
signal_track = ["WAK_SGN4T"]
update_callback = """
function(self)
    if self.HR then
--        if LEVERS["WAK_SGN3"].aspect >= 2 then
--            return 4
--        else
            return 2
--        end
    else
        return 0
    end
end
"""
