require("src.n_tracs_soyabridge.area")
require("src.n_tracs_soyabridge.axle")
require("src.n_tracs_soyabridge.register")
require("src.n_tracs_soyabridge.track_bridge")
require("src.n_tracs_soyabridge.switch_bridge")
require("src.n_tracs_soyabridge.command")
